=== BlackBeltTechnology/collectd/collectd-jmx/src/main/resources/META-INF/jmx_1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           xmlns:jmx="http://jmx.collectd.org/xml/ns/definition"
           targetNamespace="http://jmx.collectd.org/xml/ns/definition">
    
    <xs:element name="jmx" type="jmx:JmxType">
        <xs:annotation>
            <xs:documentation>JMX configuration element used as datasource.</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:complexType name="JmxType">
        <xs:annotation>
            <xs:documentation>JMX configuration data type.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="mbeans" type="jmx:MBeansType" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>JMX MBeans representing a set of graphs.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="version" type="jmx:VersionType" fixed="1.0" use="required">
            <xs:annotation>
                <xs:documentation>Version of JMX definition file.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="MBeansType">
        <xs:annotation>
            <xs:documentation>JMX MBeans data type.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="mbean" type="jmx:MBeanType" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>JMX MBean representing a graph.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>Name of the graph set.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="MBeanType">
        <xs:annotation>
            <xs:documentation>JMX MBean data type. All attributes are returned of no one defined.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="attribute" type="jmx:MBeanAttributeType" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>JMX MBean attribute.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>Name or filter of the JMX MBean.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>Type name, it must be added to Collectd types.db.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="typeInstance" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>Type instance name.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="MBeanAttributeType">
        <xs:annotation>
            <xs:documentation>JMX MBean attribute data type.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>MBean attribute name.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="composite" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>MBean composite attribute key (only for composite attributes).</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="typeInstance" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>Type instance name.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="index" type="xs:int" use="optional">
            <xs:annotation>
                <xs:documentation>Index of attribute value in Collectd numeric values list.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" type="jmx:DataType" use="optional" default="GAUGE">
            <xs:annotation>
                <xs:documentation>Attribute data type.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="VersionType">
        <xs:annotation>
            <xs:documentation>JMX definition file version type.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]+(\.[0-9]+)*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="DataType">
        <xs:annotation>
            <xs:documentation>Data type.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="COUNTER">
                <xs:annotation>
                    <xs:documentation>
                        The input is an ever increasing number, e.g. an octet counter in a router. RRDtool should
                        compute the difference between the last update and the current one, and divide it by the
                        amount of time lapsed.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="GAUGE">
                <xs:annotation>
                    <xs:documentation>
                        The input is a rate, e.g. m/s, or should be treated as a rate, e.g. temperature.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="DERIVE">
                <xs:annotation>
                    <xs:documentation>
                        This is similar to COUNTER, except that the input can decrease. This is useful for instance
                        in a kWh meter when you produce more solar power than you use. In that case you actually do
                        get a negative rate.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ABSOLUTE">
                <xs:annotation>
                    <xs:documentation>
                        This is to be used when the counter is reset every time it is read, when people start counting
                        from zero, and so on. The main difference between ABSOLUTE and GAUGE is that the input is not
                        yet a rate, it should first be divided by time to get a rate. The main difference between
                        ABSOLUTE and COUNTER is that RRDtool should not use the previous input value to compute its
                        delta.
                    </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== BlackBeltTechnology/collectd/collectd-jmx-agent/src/main/config/ehcache-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../../../../collectd-jmx/src/main/resources/META-INF/jmx_1.0.xsd">
    <mbeans name="jmx_ehcache">
        <mbean name="net.sf.ehcache:type=CacheStatistics,CacheManager=__DEFAULT__,*" type="ehcache_objects">
            <attribute name="ObjectCount" type="GAUGE"/>
            <attribute name="DiskStoreObjectCount" type="GAUGE"/>
            <attribute name="WriterQueueLength" type="GAUGE"/>
        </mbean>
        <mbean name="net.sf.ehcache:type=CacheStatistics,CacheManager=__DEFAULT__,*" type="ehcache_stats">
            <attribute name="CacheHits" type="GAUGE"/>
            <attribute name="CacheMisses" type="GAUGE"/>
            <attribute name="InMemoryHits" type="GAUGE"/>
            <attribute name="InMemoryMisses" type="GAUGE"/>
            <attribute name="OnDiskHits" type="GAUGE"/>
            <attribute name="OnDiskMisses" type="GAUGE"/>
            <attribute name="OffHeapHits" type="GAUGE"/>
            <attribute name="OffHeapMisses" type="GAUGE"/>
        </mbean>
    </mbeans>
</jmx>

=== BlackBeltTechnology/collectd/collectd-jmx-agent/src/main/config/dbcp2-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../../../../collectd-jmx/src/main/resources/META-INF/jmx_1.0.xsd">
    <mbeans name="jmx_dbcp2">
        <mbean name="org.ops4j.pax.jdbc.pool.dbcp2:type=GenericObjectPool,*" type="dbcp2_pool">
            <attribute name="NumActive" index="0"/>
            <attribute name="NumIdle" index="1"/>
            <attribute name="MaxTotal" index="2"/>
            <attribute name="MaxIdle" index="3"/>
            <attribute name="NumWaiters" index="4"/>
        </mbean>
    </mbeans>
</jmx>

=== BlackBeltTechnology/collectd/collectd-jmx-agent/src/main/config/javalang-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../../../../collectd-jmx/src/main/resources/META-INF/jmx_1.0.xsd">
    <mbeans name="jmx_java">
        <mbean name="java.lang:type=Memory" type="jmx_memory" typeInstance="heap">
            <attribute name="HeapMemoryUsage" composite="init"/>
            <attribute name="HeapMemoryUsage" composite="committed"/>
            <attribute name="HeapMemoryUsage" composite="used"/>
            <attribute name="HeapMemoryUsage" composite="max"/>
        </mbean>
        <mbean name="java.lang:type=Memory" type="jmx_memory" typeInstance="non_heap">
            <attribute name="NonHeapMemoryUsage" composite="init"/>
            <attribute name="NonHeapMemoryUsage" composite="committed"/>
            <attribute name="NonHeapMemoryUsage" composite="used"/>
            <attribute name="NonHeapMemoryUsage" composite="max"/>
        </mbean>
        
        <mbean name="java.lang:type=MemoryPool,*" type="jmx_memory_pool">
            <attribute name="Usage" composite="init"/>
            <attribute name="Usage" composite="committed"/>
            <attribute name="Usage" composite="used"/>
            <attribute name="Usage" composite="max"/>
        </mbean>

        <mbean name="java.lang:type=Threading" type="jmx_threading" typeInstance="threads">
            <attribute name="ThreadCount"/>
            <attribute name="DaemonThreadCount"/>
        </mbean>

        <mbean name="java.lang:type=ClassLoading" type="jmx_classloading" typeInstance="classes">
            <attribute name="LoadedClassCount"/>
            <attribute name="TotalLoadedClassCount" type="COUNTER"/>
            <attribute name="UnloadedClassCount" type="COUNTER"/>
        </mbean>

        <mbean name="java.lang:type=Compilation" type="total_time_in_ms">
            <attribute name="TotalCompilationTime" typeInstance="total_compilation_time" type="DERIVE"/>
        </mbean>

        <mbean name="java.lang:type=GarbageCollector,*" type="jmx_gc">
            <attribute name="CollectionCount" type="COUNTER"/>
            <attribute name="CollectionTime" type="DERIVE"/>
        </mbean>
    </mbeans>
</jmx>

=== BlackBeltTechnology/collectd/collectd-jmx/src/main/config/dbcp2-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../resources/META-INF/jmx_1.0.xsd">
    <mbeans name="dbcp2">
        <mbean name="org.ops4j.pax.jdbc.pool.dbcp2:type=GenericObjectPool,*" alias="GenericObjectPool">
            <attribute name="NumActive" alias="active"/>
            <attribute name="NumIdle" alias="idle"/>
            <attribute name="MaxTotal" alias="max total"/>
            <attribute name="MaxIdle" alias="max idle"/>
            <attribute name="NumWaiters" alias="waiters"/>
        </mbean>
    </mbeans>
</jmx>

=== BlackBeltTechnology/collectd/collectd-jmx/src/main/config/dozer-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../resources/META-INF/jmx_1.0.xsd">
    <mbeans name="dozer">
        <mbean name="org.dozer.jmx:type=DozerStatisticsController" alias="Cache">
            <attribute name="CacheHitCount" alias="cache hits"/>
            <attribute name="CacheMissCount" alias="cache misses"/>
        </mbean>
        <mbean name="org.dozer.jmx:type=DozerStatisticsController" alias="FieldMapping">
            <attribute name="FieldMappingFailureCount" alias="field mapping failures"/>
            <attribute name="FieldMappingSuccessCount" alias="field mapping success"/>
        </mbean>
        <mbean name="org.dozer.jmx:type=DozerStatisticsController" alias="Mapping">
            <attribute name="MappingFailureCount" alias="mapping failures"/>
            <attribute name="MappingSuccessCount" alias="mapping success"/>
        </mbean>
    </mbeans>
</jmx>

=== BlackBeltTechnology/collectd/collectd-jmx/src/main/config/javalang-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../resources/META-INF/jmx_1.0.xsd">
    <mbeans name="java">
        <mbean name="java.lang:type=Memory" alias="Memory">
            <attribute name="HeapMemoryUsage.init" alias="Heap_init" units="bytes"/>
            <attribute name="HeapMemoryUsage.committed" alias="Heap_committed" units="bytes"/>
            <attribute name="HeapMemoryUsage.used" alias="Heap_used" units="bytes"/>
            <attribute name="HeapMemoryUsage.max" alias="Heap_max" units="bytes"/>
            <attribute name="NonHeapMemoryUsage.init" alias="NonHeap_init"  units="bytes"/>
            <attribute name="NonHeapMemoryUsage.committed" alias="NonHeap_committed" units="bytes"/>
            <attribute name="NonHeapMemoryUsage.used" alias="NonHeap_used" units="bytes"/>
            <attribute name="NonHeapMemoryUsage.max" alias="NonHeap_max" units="bytes"/>
        </mbean>

        <mbean name="java.lang:type=Threading" alias="Threading">
            <attribute name="ThreadCount" alias="Threads"/>
            <attribute name="DaemonThreadCount" alias="DaemonThreads"/>
        </mbean>

        <mbean name="java.lang:type=ClassLoading" alias="ClassLoading">
            <attribute name="LoadedClassCount" alias="LoadedClasses"/>
            <attribute name="TotalLoadedClassCount" alias="TotLoadedClasses"/>
            <attribute name="UnloadedClassCount" alias="UnloadedClasses"/>
        </mbean>

        <mbean name="java.lang:type=Compilation" alias="Compilation">
            <attribute name="TotalCompilationTime" alias="TotalTime"/>
        </mbean>

        <mbean name="java.lang:type=GarbageCollector,*" alias="GC">
            <attribute name="CollectionCount" type="COUNTER"/>
            <attribute name="CollectionTime" type="COUNTER"/>
        </mbean>
    </mbeans>
</jmx>

=== BlackBeltTechnology/collectd/collectd-jmx-agent/src/main/config/dozer-collectd.xml
<?xml version="1.0" encoding="UTF-8"?>
<jmx version="1.0"
     xmlns="http://jmx.collectd.org/xml/ns/definition" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:schemaLocation="http://jmx.collectd.org/xml/ns/definition ../../../../collectd-jmx/src/main/resources/META-INF/jmx_1.0.xsd">
    <mbeans name="jmx_dozer">
        <!--mbean name="org.dozer.jmx:type=DozerStatisticsController" type="dozer_cache">
            <attribute name="CacheHitCount"/>
            <attribute name="CacheMissCount"/>
        </mbean-->
        <mbean name="org.dozer.jmx:type=DozerStatisticsController" type="dozer_mapping" typeInstance="field_mapping">
            <attribute name="FieldMappingSuccessCount"/>
            <attribute name="FieldMappingFailureCount"/>
        </mbean>
        <mbean name="org.dozer.jmx:type=DozerStatisticsController" type="dozer_mapping" typeInstance="object_mapping">
            <attribute name="MappingSuccessCount"/>
            <attribute name="MappingFailureCount"/>
        </mbean>
    </mbeans>
</jmx>
